language: scala
jdk: oraclejdk8
scala:
- 2.11.8
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
script:
  - sbt clean coverage test
  - sbt coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
